### ISSUE TITLE
[Pagination] needs improvements

### ISSUE THREAD

**Issue by alihassan18** [libonomy/explorer#64]
The issue is present in the latest release.
 I have searched the issues of this repository and believe that this is not a duplicate.

### Current Behavior 😯
It does'n show 6th page when pages are more than 5, so i can't go to the 6th page by clicking the button.
### Expected Behavior 🤔
when i go to the 4th page it show me the 6th page and replace the 2nd page button to ```...``` and when i go to the 5th page it show me the 7th page button

**Comment by KashyapPavra** [comment]
Hello @alihassan18 , I would like to contribute to this issue. I had a look at this [page](http://liboexplorer.com/txs) and found the issue. 

Can you assign me this issue?

**Comment by KashyapPavra** [comment]
@alihassan18 
**Thankyou** for assigning me this issue

**Comment by KashyapPavra** [comment]
@alihassan18 I got the server running, but there are no transactions.

This [file](https://github.com/libonomy/explorer/blob/main/src/redux/txs/actions.js) ``/src/redux/txs/actions.js``
manages the state of transactions, which is fetched from an api using the ENV variables, so can you help me with getting some data that I can use to test my code?

**Comment by alihassan18** [comment]
@KashyapPavra you need to setup environment variable. Let me update README.md file I will write env details on it.

**Comment by alihassan18** [comment]
@KashyapPavra 
Create .env file in project root directory and write these lines.
REACT_APP_REST_API= YOUR_API
REACT_APP_NODE_API= YOUR_API

Due to organization restrictions i can't share ip with you, you can use dummy data.

**Comment by KashyapPavra** [comment]
@alihassan18 
ok no problem. Can you just share data fields that is being fetched, so that I can add dummy data to those fields in my API?

**Comment by alihassan18** [comment]
@KashyapPavra you can check these fields from components where they are being used.

**Comment by KashyapPavra** [comment]
@alihassan18 Figure it out, thanks!

**Comment by alihassan18** [comment]
@KashyapPavra  nearby we will display our test api so you can use it.

**Comment by alihassan18** [comment]
issue is fixed by @KashyapPavra  as a part of pr #68 so i am closing this issue.
